---
name: Publish Release
on:
  push:
    tags:
      # Publish a new version when a new tag is pushed. Tag must be a valid semver version.
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  # Create a release on GitHub when a new tag is pushed
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false